// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNCfZ6vMGlYx0PYc7YNLR9mHDo_5rV0uc',
    appId: '1:286405169123:web:12a7ab6b49cb6e3eb21ad6',
    messagingSenderId: '286405169123',
    projectId: 'bytesized-news',
    authDomain: 'bytesized-news.firebaseapp.com',
    storageBucket: 'bytesized-news.firebasestorage.app',
    measurementId: 'G-DZ52GQ6G88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUuN8jh3siOttcA26Gid-VgILXW-AX5tY',
    appId: '1:286405169123:android:4796eede57acedfab21ad6',
    messagingSenderId: '286405169123',
    projectId: 'bytesized-news',
    storageBucket: 'bytesized-news.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNCfZ6vMGlYx0PYc7YNLR9mHDo_5rV0uc',
    appId: '1:286405169123:web:70af5915f7b8b148b21ad6',
    messagingSenderId: '286405169123',
    projectId: 'bytesized-news',
    authDomain: 'bytesized-news.firebaseapp.com',
    storageBucket: 'bytesized-news.firebasestorage.app',
    measurementId: 'G-J7FNJ3G4SP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxr2z80RAHK7hVKO6DmgXWHWz2BkJt4rY',
    appId: '1:286405169123:ios:9c12da3f04b400b4b21ad6',
    messagingSenderId: '286405169123',
    projectId: 'bytesized-news',
    storageBucket: 'bytesized-news.firebasestorage.app',
    androidClientId: '286405169123-nne1dbjjskkvvqffc7ih8s7pjna4ddgp.apps.googleusercontent.com',
    iosClientId: '286405169123-kna6dihea27p7eckp8faq527csc5552n.apps.googleusercontent.com',
    iosBundleId: 'com.zeykafx.bytesizedNews',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxr2z80RAHK7hVKO6DmgXWHWz2BkJt4rY',
    appId: '1:286405169123:ios:9c12da3f04b400b4b21ad6',
    messagingSenderId: '286405169123',
    projectId: 'bytesized-news',
    storageBucket: 'bytesized-news.firebasestorage.app',
    androidClientId: '286405169123-nne1dbjjskkvvqffc7ih8s7pjna4ddgp.apps.googleusercontent.com',
    iosClientId: '286405169123-kna6dihea27p7eckp8faq527csc5552n.apps.googleusercontent.com',
    iosBundleId: 'com.zeykafx.bytesizedNews',
  );

}